# Needs a SDL2 tree in ./SDL2:
# git clone -b release-2.32.x https://github.com/mschilder123/SDL2.git
#
# TODO: submodule?

all: boxplorer2.exe shadershrink.exe edit-cfg.exe glsl-test.exe sdl2-test.exe

clean:
	del *.obj
	del boxplorer2.exe shadershrink.exe edit-cfg.exe glsl-test.exe sdl2-test.exe
	del boxplorer2.exp boxplorer2.lib

CFLAGS=/nologo /ISDL2/include /I. /Iinclude /IAntTweakBar/include /IAntTweakBar/src /ILibOVR/Include /MD /D_CONSOLE /Gm- /EHsc /GS /W3 /WX- /Ox /DTW_NO_LIB_PRAGMA /DTW_STATIC /DANT_DEBUG /std:c++17

LDFLAGS=/link /LIBPATH:SDL2/VisualC/x64/Release /LIBPATH:LibOVR/Lib/Windows/x64/Release /SUBSYSTEM:console /nologo

TW_OBJS=TwBar.obj TwFonts.obj TwMgr.obj TwColors.obj TwOpenGL.obj \
        TwPrecomp.obj LoadOGL.obj \
        TwEventSDL.obj TwEventSDL12.obj TwEventSDL13.obj TwEventSDL20.obj \
        LoadOGLCore.obj TwOpenGLCore.obj

BX_OBJECTS = boxplorer2.obj interpolate.obj uniforms.obj camera.obj shader.obj shader_procs.obj \
						 glsl.obj TGA.obj utils.obj shader_manager.obj hmd.obj

boxplorer2.exe: $(BX_OBJECTS) $(TW_OBJS) Makefile.win
	link $(LDFLAGS) $(BX_OBJECTS) $(TW_OBJS)

sdl2-test.exe: sdl2-test.cc Makefile.win
	cl $(CFLAGS) sdl2-test.cc $(LDFLAGS)

sdl2-haptic.exe: sdl2-haptic.cc Makefile.win
	cl $(CFLAGS) sdl2-haptic.cc $(LDFLAGS)

shadershrink.exe: shadershrink.cc Makefile.win
	cl $(CFLAGS) shadershrink.cc $(LDFLAGS)

glsl-test.exe: glsl-test.cc glsl.obj TGA.obj TGA.h glsl.h Makefile.win
	cl $(CFLAGS) glsl-test.cc glsl.obj TGA.obj $(LDFLAGS)

edit-cfg.exe: edit-cfg.cc Makefile.win
	cl $(CFLAGS) edit-cfg.cc $(LDFLAGS)

boxplorer2.obj: boxplorer2.cc default_shaders.h shader_procs.h TGA.h \
                glsl.h interpolate.h uniforms.h camera.h shader.h params.h hmd.h \
                cfgs\menger.cfg.data\fragment.glsl include\setup.inc \
								utils.h Makefile.win
hmd.obj: hmd.cc hmd.h
glsl.obj: glsl.cc glsl.h utils.h
interpolate.obj: interpolate.cc interpolate.h utils.h
shader.obj: shader.cc shader.h utils.h
shader_procs.obj: shader_procs.cc shader_procs.h utils.h
uniforms.obj: uniforms.cc uniforms.h shader_procs.h camera.h utils.h
camera.obj: camera.cc camera.h params.h utils.h
TGA.obj: TGA.cc TGA.h utils.h

TwBar.obj: AntTweakBar\src\TwBar.cpp
	cl $(CFLAGS) -c $**

TwMgr.obj: AntTweakBar\src\TwMgr.cpp
	cl $(CFLAGS) -c $**

TwColors.obj: AntTweakBar\src\TwColors.cpp
	cl $(CFLAGS) -c $**

TwFonts.obj: AntTweakBar\src\TwFonts.cpp
	cl $(CFLAGS) -c $**

TwEventSDL.obj: AntTweakBar\src\TwEventSDL.c
	cl $(CFLAGS) -c $**

TwEventSDL12.obj: AntTweakBar\src\TwEventSDL12.c
	cl $(CFLAGS) -c $**

TwEventSDL13.obj: AntTweakBar\src\TwEventSDL13.c
	cl $(CFLAGS) -c $**

TwEventSDL20.obj: AntTweakBar\src\TwEventSDL20.c
	cl $(CFLAGS) -c $**

TwOpenGL.obj: AntTweakBar\src\TwOpenGL.cpp
	cl $(CFLAGS) -c $**

TwOpenGLCore.obj: AntTweakBar\src\TwOpenGLCore.cpp
	cl $(CFLAGS) -c $**

TwPrecomp.obj: AntTweakBar\src\TwPrecomp.cpp
	cl $(CFLAGS) -c $**

LoadOGL.obj: AntTweakBar\src\LoadOGL.cpp
	cl $(CFLAGS) -c $**

LoadOGLCore.obj: AntTweakBar\src\LoadOGLCore.cpp
	cl $(CFLAGS) -c $**
